### ISSUE TITLE
Released version 5.2.1 is corrupted

### ISSUE THREAD

**Issue by PowerKiKi** [Roave/psr-container-doctrine#135]
Released version 5.2.1 does not contains any changes at all, as can be seen there: https://github.com/Roave/psr-container-doctrine/compare/5.2.0...5.2.1

But according to [the release notes](https://github.com/Roave/psr-container-doctrine/releases/tag/5.2.1), it should contains at the very least two commits.

That explains https://github.com/Roave/psr-container-doctrine/pull/133#issuecomment-2222465693.

Can we please get a new patch release that contains at least https://github.com/Roave/psr-container-doctrine/commit/3fcf04261545cfe19b030d215e9ec02b1ea76b43 ?

**Comment by Slamdunk** [comment]
https://github.com/Roave/psr-container-doctrine/pull/133 has been proposed againt `5.3.x` branch and I missed that error.

I'll fix this soon, sorry

**Comment by PowerKiKi** [comment]
My bad, I didn't pay attention to that when I created the PR :-/

**Comment by PowerKiKi** [comment]
https://github.com/Roave/psr-container-doctrine/releases/tag/5.2.2
