### ISSUE TITLE
Using a custom configuration key utilizes methods marked as internal

### ISSUE THREAD

**Issue by cspray** [Roave/psr-container-doctrine#139]
In the documentation on [Configuration](https://github.com/Roave/psr-container-doctrine?tab=readme-ov-file#configuration), if you want to use a configuration key other than `orm_default`, it is suggested to construct the factory and invoke it manually. Here's the relevant pieces:

```php
return [
    'dependencies' => [
        'factories' => [
            'doctrine.entity_manager.orm_other' => static fn (ContainerInterface $container) => (new EntityManagerFactory('orm_custom_key'))($container),
        ],
    ],
];
```

The methods `EntityManagerFactory::__construct` and `EntityManagerFactory::__invoke` are actually on the [AbstractFactory](https://github.com/Roave/psr-container-doctrine/blob/6f8a74f6289422c91f91cc1c5a858df6aad0bb98/src/AbstractFactory.php) class and this is marked as internal. This causes tooling to flag this example as using internal methods outside of their designated package.

This is a relatively minor issue, but ideally customizing the configuration key used by the factories should not require invoking methods marked as internal.

**Comment by Slamdunk** [comment]
Ye, I think the original purpose was to mark the `AbstractFactory` as internal rather than its methods...

I'll accept a PR that removes the `@internal` annotation :+1:
