### ISSUE TITLE
Undefined index: default_driver

### ISSUE THREAD

**Issue by eremem** [Roave/psr-container-doctrine#17]
I've just switched from the DASPRiD package and get the Laminas\ServiceManager\Exception\ServiceNotCreatedException thrown upon my previously working configuration:

> Service with name "Doctrine\ORM\EntityManager" could not be created. Reason: Undefined index: default_driver

I went through the readme and the sample configurations but found no clue as far as 'default_driver' is concerned.

What works is the following change in DriverFactory.php:71
`if (@$config['default_driver'] !== null) {`

**Comment by Ocramius** [comment]
Handled in #18

**Comment by Ocramius** [comment]
https://github.com/Roave/psr-container-doctrine/releases/tag/2.1.1 should fix this: let us know if there are further problems with it :+1:
