### ISSUE TITLE
Slice the codebase into the doctrine libraries

### ISSUE THREAD

**Issue by dominikzogg** [Roave/psr-container-doctrine#32]
Is there any interest to split this repository into pieces? one for dbal, orm, cache etc. to make it easier to resuse, for example for a version for mongodb orm?

**Comment by asgrim** [comment]
Hmm, seems a lot of overhead for such a small set of factories? been a while since I used this but if the factory is configured, it uses it right? We can always add factories for the ODM (IIRC it doesn't work at the moment indeed)

**Comment by dominikzogg** [comment]
I get that, on the other side i like the possibility to combine them as needed and still having a hard dependency on the related doctrine library behind.

**Comment by Ocramius** [comment]
I'd avoid a slice here: I maintained the slices under the `doctrine/` namespace for a while, and it was nothing but pain and coordinated releases.

Even if the dependencies are declared/unavoidable, it's an acceptable tradeoff compared to the added overhead.

**Comment by dominikzogg** [comment]
What is about adding those factories to the original (doctrine) libraries, those factories are DIC agnostic?

**Comment by dominikzogg** [comment]
@DASPRiD FYI: https://github.com/chubbyphp/chubbyphp-laminas-config-factory

**Comment by dominikzogg** [comment]
https://github.com/chubbyphp/chubbyphp-laminas-config-doctrine
- cause i prefer not to install dbal or orm if it's not in use (will probably add mongodb odm too)
- cause i prefer class names as service ids

**Comment by Ocramius** [comment]
Thanks for forking out: IMO the better approach for this specific use-case :+1:
