### ISSUE TITLE
DriverFactory incompatible with AttributeDriver

### ISSUE THREAD

**Issue by marcguyer** [Roave/psr-container-doctrine#45]
The DriverFactory assumes that any subclass of AnnotationDriver will maintain its constructor signature:

https://github.com/Roave/psr-container-doctrine/blob/607341fd2cb290010f5418c970e7a9855f6d12c0/src/DriverFactory.php#L43-L57

AttributeDriver redefines the constructor:

https://github.com/doctrine/orm/blob/f3e55fae9fdbdbc23897006bdbf016c20e11f6e9/lib/Doctrine/ORM/Mapping/Driver/AttributeDriver.php#L36-L39

I'm working around this for now with a wrapper class:

```php
<?php
declare(strict_types=1);

namespace MyData;

class AttributeDriver extends \Doctrine\ORM\Mapping\Driver\AttributeDriver
{
    /**
     * Redefine constructor to work around argument bug since
     * \Doctrine\ORM\Mapping\Driver\AttributeDriver redefined the constructor
     * and changed the arguments while the Roave factory assumes the same
     * arguments as the parent AnnotationDriver
     */
    public function __construct($reader, $paths = null)
    {
        parent::__construct($paths);
    }
}
```

**Comment by asgrim** [comment]
Fixed in #52 and released in `3.1.1` - thanks @Moln !
