### ISSUE TITLE
Class 'Doctrine\Common\Cache\ArrayCache' not found with doctrine/cache 2.x upgrade

### ISSUE THREAD

**Issue by kirkmadera** [Roave/psr-container-doctrine#46]
It appears doctrine/cache has stopped supporting pre-built caching implementations. This container needs to be updated to consider doctrine/cache 2.x. In the immediate, this should be locked into compatibility with doctrine/cache:^1.0.0.

I am currently using doctrine/cache 1.11.3 and can't confirm compatibility with versions previous to this.

I can also confirm that adding this version constraint locally fixed my issue.

**Comment by edigu** [comment]
I just had a quick look and seems like doctrine/persistence still has support for doctrine/cache ^1.11

Seems like a decision has to be made either here or somewhere else since doctrine/cache is currently an indirect dependency.

**Comment by PowerKiKi** [comment]
I created the PR #50 that would solve this issue by declaring the hard dependency that always existed.
