### ISSUE TITLE
Support doctrine/persistence 3.0 with ORM 2.12

### ISSUE THREAD

**Issue by mrVrAlex** [Roave/psr-container-doctrine#71]
Hello.
Recently released ORM v2.12 add support for persistence v3.0
Will be work solutions if allow v3 in this package, like this: "doctrine/persistence": "^2.4 || ^3"?

**Comment by Ocramius** [comment]
Check if it works, and send a patch?

**Comment by mrVrAlex** [comment]
If you mean check by unit tests - it is only one side of checking )
Few days ago I watch this discuss with popcorn https://github.com/doctrine/orm/issues/9668 and now I'm afraid to get into the intricacies between orm, dbal, persistence and cache packages - I'm definitely not expert in this))
But OK, will try because we use this package in our project...

BTW: We actually replaced doctrine module for laminas/mezzio on this package)

**Comment by Ocramius** [comment]
As I said: send a patch, run the tests, verify that CI is all green, and we can certainly merge + release :+1:

**Comment by Slamdunk** [comment]
Solved in https://github.com/Roave/psr-container-doctrine/pull/95
