### ISSUE TITLE
Replace Prophecy mocks with PHPUnit mocks

### ISSUE THREAD

**Issue by asgrim** [Roave/psr-container-doctrine#8]
As it says on the tin.

**Comment by edigu** [comment]
I would like to propose a PR for this today.

**Comment by DASPRiD** [comment]
Usually Prophecy was much more elegant that PHPUnit's internal mocks. Did that change?

**Comment by Ocramius** [comment]
Too magic, and un-typed. Phpunit mocks are generally simpler and work much
better for anything related to static analysis.

**Comment by asgrim** [comment]
Fixed by #12
